### ISSUE TITLE
Test code packaged with production code

### ISSUE THREAD

**Issue by xstefanox** [mahdikiani/singleton_package#1]
# Description

The library is packaged with the test code along with the production code.
This means that, in my project, I could use `TestSingleton`, which is something that should not happen.

# Possible solution

The `TestSingleton` class should be excluded from the package published on pypi.org.

**Comment by mahdikiani** [comment]
Could you explain more about the situation that it would be helpful to add tests on package and when I should not?

**Comment by xstefanox** [comment]
Sure, I will clarify my previous statement.

Adding tests is always a best practice, we all should cover with test our production code as much as we can.

What I wanted to explain previously is that you should not mix production code with test code. Given that this library is published on pypi.org, you should expect that other developers use it in their projects, like I recently started to do in mine.

The problem, tough, is that `singleton_package` test classes appeared in the code that I could import, along with the `Singleton` class.

Take a look to this screenshot from my PyCharm IDE: 
![immagine](https://github.com/mahdikiani/singleton_package/assets/462688/a13afd6b-5301-4e77-8a9d-d7cc3df505fc)

Currently there is only one test class, therefore the issue is negligible, but tomorrow they could be more and more, if you add more tests because you plan to add more features.

The best practice is that you do not redistribute your test code, but just production code, so you should find a way to exclude the `test.py file` from the artifact uploaded to pypi.org.

Hope this helps.

**Comment by mahdikiani** [comment]
Thank you for your suggestion. I understood your point. I will remove tests from publishing on the pypi today.

**Comment by mahdikiani** [comment]
Hi @xstefanox 
The mentioned issue has been fixed. You can update to 0.5.2 version of the package.
Do not hesitate to send any other issues.
Best regards

**Comment by mahdikiani** [comment]
version 0.5.2 fixed the issue
